### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by JIEyuUUU0818** [chenkang455/TRMD#4]
Hello author, when I am training the model using the "python train_GoPro. py -- rgb False -- savepath Model/RE-Net_GRAY. pth" command I encounter a Runtime Error: Given groups=1, weight of size [16, 3, 5, 5], expected input [8, 1, 200, 256] to have 3 channels, but got 1 channel instead. How can I correct this error?Thanks.

**Comment by chenkang455** [comment]
> Hello author, when I am training the model using the "python train_GoPro. py -- rgb False -- savepath Model/RE-Net_GRAY. pth" command I encounter a Runtime Error: Given groups=1, weight of size [16, 3, 5, 5], expected input [8, 1, 200, 256] to have 3 channels, but got 1 channel instead. How can I correct this error?Thanks.

Hi, @JIEyuUUU0818, thanks for you interst on our work, can you provide me more information like by printing the size of the input (blurry image and events)? It should be working fine as we have defined the blurry channel to be 1 as in https://github.com/chenkang455/TRMD/blob/d2a5c9d51994ad49ed421e10d3094bde84c6edb4/network.py#L8C1-L9C1.

**Comment by JIEyuUUU0818** [comment]
Thank you for your reply. I am using the Baidu Netdisk GOPRO dataset provided by you. When I use the command "python train_GoPro.Ppy -- rgb False -- savepath Model/RE-Net_GRAY. pth", the debug output is as follows:
**_blurry_channels: 3
blur_image: torch.Size([8, 1, 200, 256])
voxel: torch.Size([8, 6, 200, 256])_**
**Why does blurry_channels output 3 when RGB is set to false**
Display running error:
Traceback (most recent call last):
File "train_GoPro.py",  line 233, in <module>
train(opt)
File "train_GoPro.py", line 108, in train
res_pre = unet(blur_image,voxel)
File "/root/miniconda3/envs/TRMD/lib/python3.8/site-packages/torch/nn/modules/module.py",  line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "/root/miniconda3/envs/TRMD/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py",  line 159, in forward
return self.module(*inputs[0], **kwargs[0])
File "/root/miniconda3/envs/TRMD/lib/python3.8/site-packages/torch/nn/modules/module.py",  line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "/home/yj/Img_Rebuild/Code/TRMd/network.py",  line 101, in forward
blur1 = self.blur_en_conv1(blurry_frame)
File "/root/miniconda3/envs/TRMD/lib/python3.8/site-packages/torch/nn/modules/module.py",  line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "/root/miniconda3/envs/TRMD/lib/python3.8/site-packages/torch/nn/modules/container.py",  line 117, in forward
input = module(input)
File "/root/miniconda3/envs/TRMD/lib/python3.8/site-packages/torch/nn/modules/module.py",  line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "/root/miniconda3/envs/TRMD/lib/python3.8/site-packages/torch/nn/modules/conv.py",  line 423, in forward
return self._conv_forward(input, self.weight)
File "/root/miniconda3/envs/TRMD/lib/python3.8/site-packages/torch/nn/modules/conv.py",  line 419, in _conv_forward
return F.conv2d(input,  weight, self.bias, self.stride,
RuntimeError: Given groups=1, weight of size [16, 3, 5, 5], expected input[8, 1, 200, 256] to have 3 channels,  but got 1 channels instead
﻿

**Comment by chenkang455** [comment]
> Thank you for your reply. I am using the Baidu Netdisk GOPRO dataset provided by you. When I use the command "python train_GoPro.Ppy -- rgb False -- savepath Model/RE-Net_GRAY. pth", the debug output is as follows: **_blurry_channels: 3 blur_image: torch.Size([8, 1, 200, 256]) voxel: torch.Size([8, 6, 200, 256])_** **Why does blurry_channels output 3 when RGB is set to false** Display running error: Traceback (most recent call last): File "train_GoPro.py", line 233, in train(opt) File "train_GoPro.py", line 108, in train res_pre = unet(blur_image,voxel) File "/root/miniconda3/envs/TRMD/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/root/miniconda3/envs/TRMD/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward return self.module(*inputs[0], **kwargs[0]) File "/root/miniconda3/envs/TRMD/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/home/yj/Img_Rebuild/Code/TRMd/network.py", line 101, in forward blur1 = self.blur_en_conv1(blurry_frame) File "/root/miniconda3/envs/TRMD/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/root/miniconda3/envs/TRMD/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward input = module(input) File "/root/miniconda3/envs/TRMD/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/root/miniconda3/envs/TRMD/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward return self._conv_forward(input, self.weight) File "/root/miniconda3/envs/TRMD/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward return F.conv2d(input, weight, self.bias, self.stride, RuntimeError: Given groups=1, weight of size [16, 3, 5, 5], expected input[8, 1, 200, 256] to have 3 channels, but got 1 channels instead

Hi @JIEyuUUU0818, thanks for your feedback and your interest in our work. This is a small bug related to the reading command parser. We have fixed it and you can check it by the commit link: https://github.com/chenkang455/TRMD/commit/9d38706d0590e4be6c33d0392ac03a9d3c616121#diff-c1f73352f27ef7ecd381f6640b39558bbdbb6733e80f5763ac907178d76c1fdbR222. You can run `git checkout 9ffc5b7` if you run this project by git clone or add these codes to the `train_GoPro.py`. 

Thanks for your feedback again and you can ask me directly if you have more questions. 😊😊😊
