### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 1shifeng** [chenkang455/TRMD#6]
Hello,when running python test_GoPro.py --rgb False --load_unet True --load_path Pretrained_Model/RE_Net_GRAY.pth,Traceback (most recent call last):
  File "test_GoPro.py", line 163, in <module>
    prepare()
  File "test_GoPro.py", line 61, in prepare
    unet.load_state_dict(torch.load(opt.load_path)['state_dict'])
  File "/home/dell/anaconda3/envs/trmd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
        size mismatch for module.blur_en_conv1.0.weight: copying a param with shape torch.Size([16, 1, 5, 5]) from checkpoint, the shape in current model is torch.Size([16, 3, 5, 5]).
        size mismatch for module.pred.weight: copying a param with shape torch.Size([6, 39, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 41, 1, 1]).
        size mismatch for module.pred.bias: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([18]) appears,what's wrong with setting it to 
blurry_channels=1,
                 event_channels=6,
                 out_channels=6,
                 rgb=False):

**Comment by chenkang455** [comment]
Sry for the bug, I have updated the code in `test_GoPro.py` and you can follow the modification to run the code.

**Comment by 1shifeng** [comment]
> Sry for the bug, I have updated the code in `test_GoPro.py` and you can follow the modification to run the code.

**Comment by 1shifeng** [comment]
Then how to test on the rgb data set of go pro

**Comment by 1shifeng** [comment]
When python test_GoPro.py --rgb True --load_unet True --load_path Pretrained_Model/RE_Net_RGB.pth,Traceback (most recent call last):
  File "test_GoPro.py", line 165, in <module>
    metrics = test(test_loader)
  File "test_GoPro.py", line 79, in test
    res_pre = unet(blur_image,voxel).clip(-1,1)
  File "/home/dell/anaconda3/envs/trmd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dell/anaconda3/envs/trmd/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/dell/anaconda3/envs/trmd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dell/TRMD/network.py", line 94, in forward
    blur1 = self.blur_en_conv1(blurry_frame)
  File "/home/dell/anaconda3/envs/trmd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dell/anaconda3/envs/trmd/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/dell/anaconda3/envs/trmd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dell/anaconda3/envs/trmd/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/dell/anaconda3/envs/trmd/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Given groups=1, weight of size [16, 3, 5, 5], expected input[1, 1, 360, 640] to have 3 channels, but got 1 channels instead appears

**Comment by chenkang455** [comment]
> blur_image

Hi, @1shifeng , can you print the opt parameters by `print(opt)` for me?

**Comment by 1shifeng** [comment]
Namespace(data_path_test='Data/GOPRO/test', load_path='Pretrained_Model/RE_Net_GRAY.pth', load_unet=False, num_bin=7, rgb=False, seed=3407, test_batch_size=1)

**Comment by chenkang455** [comment]
https://github.com/chenkang455/TRMD/blob/a5a45cfa696179c6ff2a79671980a0266a7a77f8/test_GoPro.py#L159C1-L168C15

Have you update the code?

**Comment by 1shifeng** [comment]
Sorry,I didn't see it.Thank you very much.
